import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'content', 'teas');

const inf = (seconds, notes = {}) =>
  seconds.map((s, i) => ({
    n: i + 1,
    seconds: s,
    ...(notes[i] ? { notes: notes[i] } : {}),
  }));

const brew = ({ vessel, ratio, temp, gongfu, westernGrams = 3, westernVol = 250, westernTemp, western, cold }) => ({
  gongfu: { vessel, ratio, waterTemp: temp, infusions: inf(...(Array.isArray(gongfu) ? [gongfu] : [gongfu.times, gongfu.notes])) },
  western: {
    grams: westernGrams,
    volume: westernVol,
    waterTemp: westernTemp ?? temp,
    infusions: inf(...(Array.isArray(western) ? [western] : [western.times, western.notes])),
  },
  ...(cold ? { coldBrew: cold } : {}),
});

const teas = [
  {
    id: 'long-jing',
    name: 'Long Jing',
    nameNative: '龙井',
    romanization: 'Lóngjǐng',
    translation: 'Dragon Well',
    origin: { country: 'China', region: 'Xi Hu', subregion: 'Hangzhou, Zhejiang' },
    category: 'green',
    cultivar: ['Long Jing #43', 'Qunti Zhong'],
    harvest: { season: 'late March–April (Ming Qian prized)', pluckingStage: 'one bud and one or two leaves' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Hand-plucked in cool Hangzhou spring; earliest flushes fetch the highest prices.' },
      { step: 'Wither', description: 'Brief indoor wither to reduce surface moisture before the wok.' },
      { step: 'Kill-green', description: 'Pan-fired in a large wok (杀青) to halt oxidation and set the chestnut aroma.' },
      { step: 'Shaping', description: 'Pressed and flattened in the wok into the characteristic sword-like leaf.' },
      { step: 'Final dry', description: 'Low-fire drying to lock the jade colour and toasted-bean sweetness.' },
    ],
    profile: {
      aroma: ['toasted chestnut', 'young soybean', 'dried grass'],
      taste: ['chestnut', 'sweet pea', 'mineral'],
      mouthfeel: 'silky, medium body without astringency when brewed cool',
      finish: 'lingering toasted-nut sweetness',
    },
    brewing: brew({
      vessel: 'gaiwan or glass',
      ratio: '1:20',
      temp: 80,
      gongfu: { times: [20, 15, 25, 40, 60], notes: { 0: 'optional 3s rinse; first steep shows the chestnut core' } },
      western: [90, 120],
      cold: { grams: 8, volume: 500, hours: 6, notes: 'Bright, sweet, almost no bitterness.' },
    }),
    water: 'Soft water, 30–80 ppm. Alkaline tap water greys the liquor and dulls the nutty top notes.',
    storage: 'Airtight, cool, away from light and pantry odours. Drink within 9 months of harvest.',
    qualityMarkers: ['flat, even, intact leaves', 'pale jade liquor', 'chestnut aroma without smoke', 'Ming Qian harvest date'],
    commonFaults: ['smoky wok', 'yellowed older leaf', 'bitter overbrew', 'musty storage'],
    similarTo: ['an-ji-bai-cha', 'tai-ping-hou-kui', 'huangshan-mao-feng'],
    summary: 'Pan-fired Hangzhou green tea: flattened leaves, chestnut sweetness, and the template for Chinese green-tea craft.',
  },
  {
    id: 'bi-luo-chun',
    name: 'Bi Luo Chun',
    nameNative: '碧螺春',
    romanization: 'Bìluóchūn',
    translation: 'Green Snail Spring',
    origin: { country: 'China', region: 'Dongting', subregion: 'Taihu, Jiangsu' },
    category: 'green',
    cultivar: ['Dongting local'],
    harvest: { season: 'late March–early April', pluckingStage: 'one bud and one tiny leaf, extremely fine' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Minute buds picked around orchards of peach, plum and loquat.' },
      { step: 'Kill-green', description: 'Gentle pan-fire; fruit-blossom aromatics from neighbouring trees cling to the downy buds.' },
      { step: 'Rolling', description: 'Rolled into tight spirals — the “green snails”.' },
      { step: 'Dry', description: 'Finished at low heat so the white pekoe remains visible.' },
    ],
    profile: {
      aroma: ['orchid', 'unripe peach', 'fresh hay'],
      taste: ['floral', 'sweet green', 'stone fruit'],
      mouthfeel: 'delicate, slightly viscous from the down',
      finish: 'short floral aftertaste',
    },
    brewing: brew({
      vessel: 'glass or small gaiwan',
      ratio: '1:25',
      temp: 75,
      gongfu: [15, 15, 25, 40],
      western: { times: [75, 100], notes: { 0: 'leaves can be dropped onto water to watch them unfurl' } },
      cold: { grams: 7, volume: 500, hours: 5 },
    }),
    water: 'Very soft water; high mineral content flattens the floral top.',
    storage: 'Refrigerate sealed if keeping past early summer. Hygroscopic down picks up fridge smells — double-bag.',
    qualityMarkers: ['tight spirals covered in pekoe', 'intense floral hit on dry leaf', 'pale gold-green liquor'],
    commonFaults: ['large coarse leaf sold as Bi Luo Chun', 'sour under-fired green', 'perfume-like added flavour'],
    similarTo: ['huangshan-mao-feng', 'an-ji-bai-cha', 'long-jing'],
    summary: 'Downy spiral greens from Taihu orchards, famous for a floral, fruity lift unusual among pan-fired greens.',
  },
  {
    id: 'huangshan-mao-feng',
    name: 'Huangshan Mao Feng',
    nameNative: '黄山毛峰',
    romanization: 'Huángshān Máofēng',
    translation: 'Yellow Mountain Fur Peak',
    origin: { country: 'China', region: 'Huangshan', subregion: 'Anhui' },
    category: 'green',
    cultivar: ['Huangshan local', 'Shi Feng'],
    harvest: { season: 'Qing Ming through Guyu', pluckingStage: 'plump bud with one or two leaves, visible pekoe' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'High-mountain spring flush from misty Yellow Mountain gardens.' },
      { step: 'Kill-green', description: 'Pan-fired to a lighter toast than Long Jing, preserving floral-orchard notes.' },
      { step: 'Shaping', description: 'Slightly twisted, not flattened; buds keep their “peak” silhouette.' },
      { step: 'Bake-dry', description: 'Gentle charcoal or electric dry.' },
    ],
    profile: {
      aroma: ['orchid', 'fresh bamboo', 'honeyed green'],
      taste: ['sweet grass', 'apricot', 'mineral'],
      mouthfeel: 'soft, round, low astringency',
      finish: 'clean mountain-water finish',
    },
    brewing: brew({
      vessel: 'gaiwan',
      ratio: '1:20',
      temp: 80,
      gongfu: [20, 20, 30, 45, 70],
      western: [90, 130],
      cold: { grams: 8, volume: 500, hours: 6 },
    }),
    water: 'Soft to lightly mineral. A touch of calcium can sharpen the mountain finish.',
    storage: 'Airtight, cool, dark. Best within the harvest year.',
    qualityMarkers: ['intact furred buds', 'uniform olive-green', 'orchid aroma without smoke'],
    commonFaults: ['broken fannings', 'stale hay', 'over-fired toast'],
    similarTo: ['tai-ping-hou-kui', 'bi-luo-chun', 'liu-an-gua-pian'],
    summary: 'Anhui high-mountain green with orchid aroma and a plump, pekoe-dusted leaf.',
  },
  {
    id: 'liu-an-gua-pian',
    name: 'Liu An Gua Pian',
    nameNative: '六安瓜片',
    romanization: 'Lù\'ān Guāpiàn',
    translation: 'Melon Seed',
    origin: { country: 'China', region: 'Lu\'an', subregion: 'Dabie Mountains, Anhui' },
    category: 'green',
    cultivar: ['Qunti'],
    harvest: { season: 'Guyu, later than most greens', pluckingStage: 'second leaf only — buds and stems removed' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck and sort', description: 'Buds and stems are stripped; only the second leaf is kept.' },
      { step: 'Bake', description: 'Unique sequential baking rather than a single wok kill-green.' },
      { step: 'Shape', description: 'Leaves take a melon-seed silhouette, slightly cupped.' },
      { step: 'Charcoal finish', description: 'A last charcoal pass adds a faint cooked-melon warmth without true roast.' },
    ],
    profile: {
      aroma: ['cooked melon', 'orchid', 'toasted leaf'],
      taste: ['sweet vegetal', 'pumpkin seed', 'gentle toast'],
      mouthfeel: 'thick for a green, almost broth-like',
      finish: 'warm, lingering sweetness',
    },
    brewing: brew({
      vessel: 'gaiwan',
      ratio: '1:18',
      temp: 85,
      gongfu: [25, 20, 30, 45, 70],
      western: [120, 150],
    }),
    water: 'Medium-soft. A little more heat than typical greens is welcome.',
    storage: 'Airtight; the baked finish keeps slightly longer than unbaked greens.',
    qualityMarkers: ['uniform seed-shaped leaves without stems', 'deep jade', 'melon-seed aroma'],
    commonFaults: ['stemmy cheap grades', 'charcoal smoke', 'thin liquor'],
    similarTo: ['huangshan-mao-feng', 'tai-ping-hou-kui', 'long-jing'],
    summary: 'The only classic Chinese green made solely from leaves, baked into a melon-seed shape with unusual body.',
  },
  {
    id: 'tai-ping-hou-kui',
    name: 'Tai Ping Hou Kui',
    nameNative: '太平猴魁',
    romanization: 'Tàipíng Hóukuí',
    translation: 'Peaceful Monkey Leader',
    origin: { country: 'China', region: 'Huangshan', subregion: 'Hou Keng, Anhui' },
    category: 'green',
    cultivar: ['Shi Da Cha'],
    harvest: { season: 'Qing Ming to Guyu', pluckingStage: 'one bud between two long leaves, pressed flat' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Large-leaf Shi Da Cha, buds nested between two leaves.' },
      { step: 'Press', description: 'Pressed between cloths into long, flat “lances” up to 15 cm.' },
      { step: 'Bake', description: 'Repeated baking over charcoal to dry without breaking the silhouette.' },
    ],
    profile: {
      aroma: ['orchid', 'fresh sugarcane', 'wet stone'],
      taste: ['sweet vegetal', 'chestnut edge', 'mineral'],
      mouthfeel: 'juicy, surprisingly full for a green',
      finish: 'long orchid-cane sweetness',
    },
    brewing: brew({
      vessel: 'tall glass',
      ratio: '1:30',
      temp: 85,
      gongfu: { times: [30, 25, 40, 60], notes: { 0: 'leaves need space to stand upright' } },
      westernGrams: 2.5,
      westernVol: 300,
      western: [150],
    }),
    water: 'Soft, cool-side 85 °C. Overheating turns the long leaf bitter.',
    storage: 'Keep flat if possible; the leaves crush easily. Drink within the year.',
    qualityMarkers: ['straight, intact two-leaf spears', 'pale veins visible', 'orchid aroma', 'no broken fragments'],
    commonFaults: ['machine-flattened fakes', 'shattered leaf', 'grassy cheap cousins'],
    similarTo: ['huangshan-mao-feng', 'long-jing', 'an-ji-bai-cha'],
    summary: 'Dramatic pressed-leaf green from Hou Keng: orchid-cane aroma and a liquor that looks like a vase of spears.',
  },
  {
    id: 'an-ji-bai-cha',
    name: 'An Ji Bai Cha',
    nameNative: '安吉白茶',
    romanization: 'Ānjí Báichá',
    translation: 'Anji White Tea',
    origin: { country: 'China', region: 'Anji', subregion: 'Zhejiang' },
    category: 'green',
    cultivar: ['Bai Ye Yi Hao'],
    harvest: { season: 'pre-Qing Ming pale flush', pluckingStage: 'one bud and one leaf while the leaf is still yellow-white' },
    oxidation: 0,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Harvested in a narrow window when chlorophyll is suppressed by cool nights.' },
      { step: 'Kill-green', description: 'Light pan-fire; processed as green tea despite the “white” name.' },
      { step: 'Dry', description: 'Quick dry to keep the pale colour and high amino-acid sweetness.' },
    ],
    profile: {
      aroma: ['fresh soybean', 'lilac', 'cream'],
      taste: ['umami', 'sweet corn', 'soft floral'],
      mouthfeel: 'brothy, almost gyokuro-like viscosity',
      finish: 'savoury-sweet, very little bite',
    },
    brewing: brew({
      vessel: 'gaiwan or glass',
      ratio: '1:20',
      temp: 75,
      gongfu: [20, 15, 25, 40, 60],
      western: [80, 110],
      cold: { grams: 7, volume: 500, hours: 5, notes: 'Exceptional cold: pure umami.' },
    }),
    water: 'Very soft. This tea is mostly theanine; minerals mute it.',
    storage: 'Freeze sealed extra if you want the pale colour to last; otherwise cool pantry for a few months.',
    qualityMarkers: ['pale yellow-green dry leaf', 'high umami', 'lime-jade liquor', 'Bai Ye cultivar'],
    commonFaults: ['green Anji sold as Bai Cha after the pale window', 'thin later flushes', 'overbrewed bitterness'],
    similarTo: ['long-jing', 'gyokuro', 'kabusecha'],
    summary: 'A green tea in process, “white” only in cultivar colour: high theanine, creamy umami, lime-pale liquor.',
  },
  {
    id: 'bai-hao-yin-zhen',
    name: 'Bai Hao Yin Zhen',
    nameNative: '白毫银针',
    romanization: 'Báiháo Yínzhēn',
    translation: 'Silver Needle',
    origin: { country: 'China', region: 'Fuding', subregion: 'Fujian' },
    category: 'white',
    cultivar: ['Da Bai', 'Da Hao'],
    harvest: { season: 'early spring', pluckingStage: 'unopened buds only' },
    oxidation: 8,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Only the fat, down-covered bud.' },
      { step: 'Wither', description: 'Long indoor/outdoor wither; the defining “process” of white tea.' },
      { step: 'Dry', description: 'Sun or low bake. No roll, no kill-green.' },
    ],
    profile: {
      aroma: ['hay', 'melon', 'white peach', 'cocoa husk'],
      taste: ['delicate fruit', 'cucumber', 'honey'],
      mouthfeel: 'silky, light-bodied, cooling',
      finish: 'soft sweetness, no tannin if not oversteeped',
    },
    brewing: brew({
      vessel: 'gaiwan',
      ratio: '1:20',
      temp: 85,
      gongfu: { times: [45, 30, 45, 70, 90], notes: { 0: 'buds are slow to open; patience on steep one' } },
      western: [180, 240],
      cold: { grams: 10, volume: 500, hours: 8 },
    }),
    water: 'Soft to medium. Avoid chlorine; it reads as medicine on downy buds.',
    storage: 'Ages gracefully if kept dry and odour-free. Young for florals; 3–7 years for honey-amber.',
    qualityMarkers: ['plump silver buds, no leaf', 'even down', 'sweet hay, not sour', 'Fuding Da Bai'],
    commonFaults: ['needles mixed with leaf (that is Bai Mu Dan)', 'sour wither', 'warehouse must'],
    similarTo: ['bai-mu-dan', 'shou-mei', 'jun-shan-yin-zhen'],
    summary: 'The most bud-pure white tea: silver needles, slow wither, melon-hay sweetness.',
  },
  {
    id: 'bai-mu-dan',
    name: 'Bai Mu Dan',
    nameNative: '白牡丹',
    romanization: 'Báimǔdān',
    translation: 'White Peony',
    origin: { country: 'China', region: 'Fuding', subregion: 'Fujian' },
    category: 'white',
    cultivar: ['Da Bai', 'Shui Xian'],
    harvest: { season: 'spring', pluckingStage: 'one bud and one or two leaves' },
    oxidation: 12,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Bud-and-leaf sets, more body than Yin Zhen.' },
      { step: 'Wither', description: 'Extended wither develops muscatel-honey notes.' },
      { step: 'Dry', description: 'Sun and/or indoor dry.' },
    ],
    profile: {
      aroma: ['peony', 'dried apricot', 'honey', 'hay'],
      taste: ['stone fruit', 'mild tannin', 'floral'],
      mouthfeel: 'rounder than Yin Zhen, light amber',
      finish: 'honeyed, faintly woody',
    },
    brewing: brew({
      vessel: 'gaiwan or pot',
      ratio: '1:18',
      temp: 90,
      gongfu: [30, 25, 40, 55, 80],
      western: [150, 210],
      cold: { grams: 10, volume: 500, hours: 8 },
    }),
    water: 'Medium-soft; a little more mineral than Yin Zhen can support the leaf tannin.',
    storage: 'Excellent ager. Keep dry; white tea loves humidity too much.',
    qualityMarkers: ['clear bud-and-leaf sets', 'grey-green leaf with silver buds', 'apricot-honey aroma'],
    commonFaults: ['brown, over-oxidised cheap white', 'dusty fannings', 'smoke from careless drying'],
    similarTo: ['bai-hao-yin-zhen', 'shou-mei', 'an-ji-bai-cha'],
    summary: 'White peony: bud plus leaf, more colour and apricot-honey than Silver Needle, still a wither-only tea.',
  },
  {
    id: 'shou-mei',
    name: 'Shou Mei',
    nameNative: '寿眉',
    romanization: 'Shòuméi',
    translation: 'Longevity Eyebrow',
    origin: { country: 'China', region: 'Fuding', subregion: 'Fujian' },
    category: 'white',
    cultivar: ['Da Bai', 'Qunti'],
    harvest: { season: 'late spring and autumn', pluckingStage: 'more leaf than bud, later pluck' },
    oxidation: 18,
    roast: 'none',
    processing: [
      { step: 'Pluck', description: 'Later, coarser leaf than Bai Mu Dan.' },
      { step: 'Wither and dry', description: 'Same white-tea path; often pressed into cakes for aging.' },
    ],
    profile: {
      aroma: ['dried herb', 'jujube', 'hay', 'wood'],
      taste: ['date', 'mild spice', 'husky tea'],
      mouthfeel: 'thicker, more rustic than Bai Mu Dan',
      finish: 'warming, good for aged cake brewing',
    },
    brewing: brew({
      vessel: 'clay pot or gaiwan',
      ratio: '1:15',
      temp: 95,
      gongfu: [20, 15, 25, 40, 60, 90],
      western: [180, 240],
      cold: { grams: 12, volume: 500, hours: 10 },
    }),
    water: 'Can take mineral water and near-boiling when aged.',
    storage: 'The white tea most often aged; cakes breathe slowly in a dry-cabinet.',
    qualityMarkers: ['clean herb-jujube, not compost', 'whole leaf in cakes', 'red-amber aged liquor'],
    commonFaults: ['wet-stored sourness', 'dirt-cheap broken leaf', 'smoke'],
    similarTo: ['bai-mu-dan', 'sheng-puer-aged', 'liu-bao'],
    summary: 'The rustic white: later leaf, date-and-herb depth, and the usual candidate for aging into cakes.',
  },
];

await mkdir(outDir, { recursive: true });
for (const tea of teas) {
  const { id, ...data } = tea;
  await writeFile(join(outDir, `${id}.json`), JSON.stringify(data, null, 2) + '\n');
}
console.log(`Wrote ${teas.length} teas to ${outDir}`);
